# Generated by Django 4.2.10 on 2024-02-23 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_alter_curso_nivel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['-data_do_curso'], 'verbose_name': 'Cadastro de curso', 'verbose_name_plural': 'Cadastros de cursos'},
        ),
    ]
